#!/usr/bin/env bash
# Deploys the Releash demo stack and checks the deployed vault against what was intended.
#
#   script/deploy.sh 31337                 local anvil, broadcasts
#   script/deploy.sh 46630                 Robinhood testnet, DRY RUN (simulation only)
#   script/deploy.sh 46630 --broadcast     Robinhood testnet, broadcast + Blockscout verify
#
# Addresses are never typed: WORLD_SIGNER and KEEPER are derived from their private keys.
# 46630 keys: DEPLOYER_PK from .env.deployer; every other key from .env.46630, which this script
# creates (cast wallet new) and writes BEFORE anything uses it. Both files are gitignored.
# Env: HALF_LIFE (default 120), RPC_URL (default per chain).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
CHAIN_ID="${1:?usage: script/deploy.sh <chainId> [--broadcast|--dry-run]}"
MODE="${2:-}"
HALF_LIFE="${HALF_LIFE:-120}"

die() { echo "deploy.sh: $*" >&2; exit 1; }
newkey() { cast wallet new --json | jq -r '.[0].private_key'; }

case "$CHAIN_ID" in
  31337)
    RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
    # anvil #0 (deployer + keeper) and #1 (world signer)
    DEPLOYER_PK="${DEPLOYER_PK:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
    WORLD_SIGNER_PK="${WORLD_SIGNER_PK:-0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d}"
    KEEPER_PK="${KEEPER_PK:-$DEPLOYER_PK}"
    MODE="${MODE:---broadcast}"
    VERIFY=()
    ;;
  46630)
    RPC_URL="${RPC_URL:-https://rpc.testnet.chain.robinhood.com}"
    [ -f .env.deployer ] || die ".env.deployer missing"
    DEPLOYER_PK="$(sed -n 's/^DEPLOYER_PK=//p' .env.deployer)"
    [ -n "$DEPLOYER_PK" ] || die "DEPLOYER_PK not in .env.deployer"
    ENVF=".env.46630"
    if [ ! -f "$ENVF" ]; then
      git check-ignore -q "$ENVF" || die "$ENVF would not be gitignored; refusing to write keys"
      umask 077
      {
        echo "# Releash actors on Robinhood testnet (46630). Generated by script/deploy.sh. Never commit."
        echo "CHAIN_ID=46630"
        echo "RPC_URL=$RPC_URL"
        echo "WORLD_SIGNER_PK=$(newkey)"
        echo "AGENT_PK=$(newkey)"
        echo "KEEPER_PK=$DEPLOYER_PK"
        echo "ALICE_PK=$(newkey)"
        echo "CONTROL_PK=$(newkey)"
        echo "LIQUIDATOR_PK=$(newkey)"
      } > "$ENVF"
      echo "wrote $ENVF (new keys)"
    fi
    WORLD_SIGNER_PK="$(sed -n 's/^WORLD_SIGNER_PK=//p' "$ENVF")"
    KEEPER_PK="$(sed -n 's/^KEEPER_PK=//p' "$ENVF")"
    MODE="${MODE:---dry-run}"
    VERIFY=(--verify --verifier blockscout --verifier-url https://explorer.testnet.chain.robinhood.com/api/)
    ;;
  *) die "unknown chain $CHAIN_ID (31337 or 46630)" ;;
esac

[ -n "$WORLD_SIGNER_PK" ] && [ -n "$KEEPER_PK" ] || die "WORLD_SIGNER_PK / KEEPER_PK missing"
WORLD_SIGNER="$(cast wallet address "$WORLD_SIGNER_PK")"
KEEPER="$(cast wallet address "$KEEPER_PK")"
DEPLOYER="$(cast wallet address "$DEPLOYER_PK")"
RPC_CHAIN="$(cast chain-id --rpc-url "$RPC_URL")" || die "RPC $RPC_URL unreachable"
[ "$RPC_CHAIN" = "$CHAIN_ID" ] || die "RPC $RPC_URL is chain $RPC_CHAIN, not $CHAIN_ID"

echo "chain $CHAIN_ID  rpc $RPC_URL  mode $MODE"
echo "deployer     $DEPLOYER  balance $(cast balance "$DEPLOYER" --rpc-url "$RPC_URL" --ether) ETH"
echo "worldSigner  $WORLD_SIGNER  (derived from WORLD_SIGNER_PK)"
echo "keeper       $KEEPER"
echo "halfLife     $HALF_LIFE s"

OUT="deployments/$CHAIN_ID.json"
export DEPLOYER_PK WORLD_SIGNER KEEPER HALF_LIFE

if [ "$MODE" = "--dry-run" ]; then
  # Deploy.s.sol writes deployments/<chainId>.json even in simulation: keep the real file intact.
  BACKUP=""
  if [ -f "$OUT" ]; then BACKUP="$(mktemp)"; cp "$OUT" "$BACKUP"; fi
  restore() { if [ -n "$BACKUP" ]; then mv "$BACKUP" "$OUT"; else rm -f "$OUT"; fi; }
  trap restore EXIT
  forge script script/Deploy.s.sol --rpc-url "$RPC_URL" --sender "$DEPLOYER"
  SIM_SIGNER="$(jq -r .worldSigner "$OUT")"; SIM_HL="$(jq -r .halfLife "$OUT")"
  [ "$(echo "$SIM_SIGNER" | tr A-F a-f)" = "$(echo "$WORLD_SIGNER" | tr A-F a-f)" ] || die "simulated worldSigner $SIM_SIGNER != $WORLD_SIGNER"
  [ "$SIM_HL" = "$HALF_LIFE" ] || die "simulated halfLife $SIM_HL != $HALF_LIFE"
  echo "DRY RUN OK: simulation would deploy vault with worldSigner $SIM_SIGNER, halfLife $SIM_HL. Nothing broadcast; $OUT untouched."
  exit 0
fi

[ "$MODE" = "--broadcast" ] || die "mode must be --broadcast or --dry-run"
forge script script/Deploy.s.sol --rpc-url "$RPC_URL" --broadcast ${VERIFY[@]+"${VERIFY[@]}"}

VAULT="$(jq -r .vault "$OUT")"
GOT_SIGNER="$(cast call "$VAULT" "worldSigner()(address)" --rpc-url "$RPC_URL")"
GOT_HL="$(cast call "$VAULT" "halfLife()(uint256)" --rpc-url "$RPC_URL" | awk '{print $1}')"
if [ "$(echo "$GOT_SIGNER" | tr A-F a-f)" != "$(echo "$WORLD_SIGNER" | tr A-F a-f)" ] || [ "$GOT_HL" != "$HALF_LIFE" ]; then
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&2
  echo "DEPLOYED VAULT $VAULT DOES NOT MATCH INTENT" >&2
  echo "  worldSigner on chain $GOT_SIGNER, intended $WORLD_SIGNER" >&2
  echo "  halfLife    on chain $GOT_HL, intended $HALF_LIFE" >&2
  echo "Both are immutable: redeploy. Do not use this vault." >&2
  exit 1
fi
echo "OK: vault $VAULT  worldSigner $GOT_SIGNER  halfLife $GOT_HL"
